language: java

jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

install:
  - npm install npm@8.5.5
  - node -v

script:
  - "./gradlew clean build"
  - npm run build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - inseon0731@naver.com