language: java

jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - npm init

install:
  - echo "Test(install)"
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - source ~/.bashrc
  - nvm install 16.15.0
  - npm update

  - node -v
  - npm -v

script:
  - "./gradlew clean build"
  - npm run build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - inseon0731@naver.com

after_success:
  - echo "Test Success"