language: java

jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get install build-essential

script:
  - "./gradlew clean build"
  - npm run build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - inseon0731@naver.com