spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/movielog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  logging.level:
    org.hibernate.SQL: debug

  sql:
    init:
      mode: always
